postgresql://billing_db_wxzy_user:8A8e2QgXyJhlHiu3dYbbSJdGWLEzjsxG@dpg-d78vbttactks73csfhv0-a.oregon-postgres.render.com/billing_db_wxzy
spring.datasource.username=billing_db_wxzy_user
spring.datasource.password=8A8e2QgXyJh1Hiu3dYbbSJdGWLEzjsxG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true