spring.datasource.url=jdbc:postgresql://dpg-d78vbttackts73csfhv0-a:5432/billing_db_wxzy
spring.datasource.username=billing_db_wxzy_user
spring.datasource.password=8A8e2QgXyJh1Hiu3dYbbSJdGWLEzjsxG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true